global using UserQuery.BusinessObjects.Interfaces;
global using System.Text.Json;
global using Microsoft.Extensions.Caching.Distributed;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using UserQuery.Core.Cache;
global using UserQuery.Core.Controllers;
global using UserQuery.Core.Interators;
global using UserQuery.Core.Presenters;